AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.1
  Exclude:
    - "bin/*.rb"

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - lib/decidim_metabase/object/filesystem_card.rb

Style/OptionalBooleanParameter:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Enabled: true
  Exclude:
    - spec/api/collection_spec.rb
  Max: 130

Metrics/AbcSize:
  Enabled: false


Metrics/ModuleLength:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Enabled: false